<%
ui.decorateWith("appui","standardEmrPage"); ui.includeCss("patienthandover","patienthandover.css")
def message=session.getAttribute("trolleyMessage",String.class); def error=session.getAttribute("trolleyError",String.class)
if(message!=null)session.setAttribute("trolleyMessage",null); if(error!=null)session.setAttribute("trolleyError",null)
def pendingHandover=binding.hasVariable("handovers")?handovers.find{it.status=="PENDING"}:null
def canEdit=binding.hasVariable("canEdit")?binding.getVariable("canEdit"):false
%>
<script>var breadcrumbs=[{icon:"icon-home",link:'/'+OPENMRS_CONTEXT_PATH+'/index.htm'},{label:"Emergency Trolley"}];</script>
<div class="ph-page"><h2>Make Emergency Trolley Handover</h2>${ui.includeFragment("patienthandover","handoverNavigation",[activeTab:"trolley"])}
<%if(message){%><div class="ph-alert ph-alert-success ph-dismissible">${message}<button type="button" onclick="dismissNotice(this)">&times;</button></div><%}%><%if(error){%><div class="ph-alert ph-alert-error ph-dismissible">${error}<button type="button" onclick="dismissNotice(this)">&times;</button></div><%}%>
<%if(currentLocation==null){%><div class="ph-alert ph-alert-error">Select a login location.</div><%}else{%><div class="ph-location-card"><strong>Location:</strong> ${currentLocation.name}</div>
<%if(canCreate&&!items.isEmpty()&&pendingHandover==null){%><section class="ph-trolley-section"><h3>Make Trolley Handover</h3><div class="ph-list-actions"><button type="button" id="toggleTrolleyItems" onclick="toggleAllTrolleyItems()">View All Items</button></div><p class="ph-help">All permanent items are included. Page buttons only change what is visible; all entered quantities remain in this transaction.</p><form method="post"><input type="hidden" name="action" value="submitHandover"/><div class="ph-inline-form"><label>Shift<select name="shift" required><option value="">Select</option><option>DAY</option><option>NIGHT</option></select></label><label>Receiving Provider<select name="receivingProviderId" required><option value="">Select</option><%providers.each{p->if(!p.retired){%><option value="${p.providerId}">${p.name}</option><%}}%></select></label></div><div class="ph-table-scroll"><table class="ph-table ph-compact-table"><thead><tr><th>Item</th><th>Previous Quantity</th><th>Handover Quantity</th><th>Short Note</th></tr></thead><tbody><%items.each{i->%><tr class="trolley-handover-row ${i.currentQuantity == 0 ? 'ph-zero-quantity' : ''}"><td>${i.itemName}</td><td>${i.currentQuantity}</td><td><input type="number" min="0" step="0.01" name="quantity_${i.id}" value="${i.currentQuantity}" required/></td><td><input name="note_${i.id}" value="${i.standardNote?:''}" placeholder="Optional note"/></td></tr><%}%></tbody></table></div><div id="trolleyEditorPagination" class="ph-editor-pagination"></div><button>Submit Trolley Handover</button></form></section><%}else if(items.isEmpty()){%><div class="ph-alert ph-alert-info">No trolley items exist. Open Emergency Trolley Items to add or upload the permanent list.</div><%}else if(!canCreate){%><div class="ph-alert ph-alert-info">You need the Patient Handover: Create privilege to make an emergency trolley handover.</div><%}else if(pendingHandover!=null){%><div class="ph-alert ph-alert-info">A pending trolley handover already exists. It must be received, corrected, or cancelled before a new trolley handover can be made.</div><%}%>
<%if(pendingHandover!=null){%><section class="ph-trolley-section"><h3>Pending Trolley Handover</h3><div class="ph-list-actions"><button type="button" id="togglePendingTrolleyItems" onclick="toggleAllPendingTrolleyItems()">View All Items</button></div><p><strong>${pendingHandover.transactionReference}</strong> | ${pendingHandover.shift} | Receiving Provider: ${pendingHandover.receivingProvider?.name}</p><div class="ph-table-scroll"><table class="ph-table ph-compact-table"><thead><tr><th>Item</th><th>Previous</th><th>Handed</th><th>Note</th><th>Correction</th></tr></thead><tbody><%pendingHandover.items.each{x->%><tr class="pending-trolley-row ${x.handedQuantity == 0 ? 'ph-zero-quantity' : ''}"><td>${x.itemNameSnapshot}</td><td>${x.previousQuantity}</td><td>${x.handedQuantity}</td><td>${x.note?:'-'}</td><td><%if(canEdit){%><details class="ph-edit-panel"><summary>Edit</summary><form method="post"><input type="hidden" name="action" value="editPendingItem"/><input type="hidden" name="handoverUuid" value="${pendingHandover.uuid}"/><input type="hidden" name="handoverItemUuid" value="${x.uuid}"/><label>Quantity<input type="number" min="0" step="0.01" name="handedQuantity" value="${x.handedQuantity}" required/></label><label>Note<input name="note" value="${x.note?:''}"/></label><label>Edit reason<input name="editReason" maxlength="1000" required/></label><button>Save Item Correction</button></form></details><%}else{%>-<%}%></td></tr><%}%></tbody></table></div><div id="pendingTrolleyPagination" class="ph-editor-pagination"></div><%if(canReceive){%><form method="post"><input type="hidden" name="action" value="receiveHandover"/><input type="hidden" name="handoverUuid" value="${pendingHandover.uuid}"/><button>Mark Entire Trolley Handover as Received</button></form><%}%>
<%if(canEdit){%><details class="ph-edit-panel ph-reassign-panel"><summary>Reassign Receiving Provider</summary><form method="post"><input type="hidden" name="action" value="reassignHandover"/><input type="hidden" name="handoverUuid" value="${pendingHandover.uuid}"/><label><strong>New receiving provider</strong><select name="receivingProviderId" required><option value="">Select</option><%providers.each{p->if(!p.retired){%><option value="${p.providerId}">${p.name}</option><%}}%></select></label><label><strong>Reason</strong><input name="editReason" maxlength="1000" required/></label><button>Reassign Trolley Handover</button></form></details><%}%><%if(canCancel){%><form method="post" class="ph-cancel-form" onsubmit="return confirm('Cancel this trolley handover? This cannot be undone.');"><input type="hidden" name="action" value="cancelHandover"/><input type="hidden" name="handoverUuid" value="${pendingHandover.uuid}"/><label><strong>Cancellation reason</strong><input name="cancellationReason" maxlength="1000" required/></label><button class="ph-cancel-button">Cancel Trolley Handover</button></form><%}%></section><%}%><%}%></div>
<script>
function dismissNotice(button){var box=button.parentNode;if(box)box.style.display='none';}
var showAllTrolleyItems=false,showAllPendingTrolleyItems=false;
function toggleAllTrolleyItems(){showAllTrolleyItems=!showAllTrolleyItems;var b=document.getElementById('toggleTrolleyItems');if(b)b.innerHTML=showAllTrolleyItems?'Show 10 Items Per Page':'View All Items';paginateTrolleyEditor(1);}
function toggleAllPendingTrolleyItems(){showAllPendingTrolleyItems=!showAllPendingTrolleyItems;var b=document.getElementById('togglePendingTrolleyItems');if(b)b.innerHTML=showAllPendingTrolleyItems?'Show 10 Items Per Page':'View All Items';paginatePendingTrolley(1);}
function updateZeroQuantityRows(){var inputs=document.querySelectorAll('input[name^="quantity_"]');for(var i=0;i<inputs.length;i++){var input=inputs[i];var row=input.closest?input.closest('tr'):input.parentNode.parentNode;if(row){if(parseFloat(input.value)===0)row.classList.add('ph-zero-quantity');else row.classList.remove('ph-zero-quantity');}input.oninput=function(){var r=this.closest?this.closest('tr'):this.parentNode.parentNode;if(parseFloat(this.value)===0)r.classList.add('ph-zero-quantity');else r.classList.remove('ph-zero-quantity');};}}
function paginateTrolleyEditor(page){var rows=document.getElementsByClassName('trolley-handover-row'),size=10,pages=Math.max(1,Math.ceil(rows.length/size));page=Math.max(1,Math.min(page,pages));for(var i=0;i<rows.length;i++)rows[i].style.display=(showAllTrolleyItems||(i>=(page-1)*size&&i<page*size))?'':'none';var box=document.getElementById('trolleyEditorPagination');if(!box)return;box.innerHTML='';if(showAllTrolleyItems)return;for(var p=1;p<=pages;p++){var b=document.createElement('button');b.type='button';b.innerHTML=p;b.disabled=p===page;b.setAttribute('data-page',p);b.onclick=function(){paginateTrolleyEditor(parseInt(this.getAttribute('data-page'),10));};box.appendChild(b);}}
function paginatePendingTrolley(page){var rows=document.getElementsByClassName('pending-trolley-row'),size=10,pages=Math.max(1,Math.ceil(rows.length/size));page=Math.max(1,Math.min(page,pages));for(var i=0;i<rows.length;i++)rows[i].style.display=(showAllPendingTrolleyItems||(i>=(page-1)*size&&i<page*size))?'':'none';var box=document.getElementById('pendingTrolleyPagination');if(!box)return;box.innerHTML='';if(showAllPendingTrolleyItems)return;for(var p=1;p<=pages;p++){var b=document.createElement('button');b.type='button';b.innerHTML=p;b.disabled=p===page;b.setAttribute('data-page',p);b.onclick=function(){paginatePendingTrolley(parseInt(this.getAttribute('data-page'),10));};box.appendChild(b);}}
paginateTrolleyEditor(1);paginatePendingTrolley(1);updateZeroQuantityRows();
</script>