<%
ui.decorateWith("appui","standardEmrPage");ui.includeCss("patienthandover","patienthandover.css")
def message=session.getAttribute("trolleyItemsMessage",String.class);def error=session.getAttribute("trolleyItemsError",String.class)
if(message!=null)session.setAttribute("trolleyItemsMessage",null);if(error!=null)session.setAttribute("trolleyItemsError",null)
%>
<script>var breadcrumbs=[{icon:"icon-home",link:'/'+OPENMRS_CONTEXT_PATH+'/index.htm'},{label:"Emergency Trolley Items"}];</script>
<div class="ph-page"><h2>Emergency Trolley Items</h2>${ui.includeFragment("patienthandover","handoverNavigation",[activeTab:"trolleyItems"])}
<%if(message){%><div class="ph-alert ph-alert-success ph-dismissible">${message}<button type="button" onclick="dismissNotice(this)" aria-label="Dismiss">&times;</button></div><%}%><%if(error){%><div class="ph-alert ph-alert-error ph-dismissible">${error}<button type="button" onclick="dismissNotice(this)">&times;</button></div><%}%>
<%if(currentLocation==null){%><div class="ph-alert ph-alert-error">Select a login location.</div><%}else{%><div class="ph-location-card"><strong>Location:</strong> ${currentLocation.name}</div>
<section class="ph-trolley-section"><h3>Add or Upload Permanent Items</h3><form method="post" class="ph-inline-form"><input type="hidden" name="action" value="addItem"/><label>Item Name<input name="itemName" required/></label><label>Starting Quantity<input type="number" min="0" step="0.01" name="startingQuantity" required/></label><label>Short Note<input name="standardNote"/></label><button>Add Item</button></form><form method="post" enctype="multipart/form-data" class="ph-upload-row"><input type="hidden" name="action" value="importItems"/><label><strong>Upload initial/new items:</strong></label><input type="file" name="trolleyFile" accept=".xlsx,.csv" required/><button>Upload Items</button><a class="ph-template-link" href="${ui.resourceLink('patienthandover','templates/emergency-trolley-items-template.csv')}">Download Upload Template</a><small>Existing item names are skipped. Uploading never removes items.</small></form></section>
<section class="ph-trolley-section ph-trolley-items-section"><h3>Current Trolley List</h3><div class="ph-list-actions"><%if(viewAll){%><a class="ph-button-link" href="${ui.pageLink('patienthandover','emergencyTrolleyItems')}">Show 10 Items Per Page</a><%}else{%><a class="ph-button-link" href="${ui.pageLink('patienthandover','emergencyTrolleyItems',[viewAll:true])}">View All Items</a><%}%></div><div class="ph-table-scroll"><table class="ph-table ph-compact-table"><thead><tr><th>Item</th><th>Current Quantity</th><th>Short Note</th><th>Action</th></tr></thead><tbody><%if(items.isEmpty()){%><tr><td colspan="4">No trolley items configured.</td></tr><%}else{items.each{i->%><tr class="${i.currentQuantity == 0 ? 'ph-zero-quantity' : ''}"><td>${i.itemName}</td><td>${i.currentQuantity}</td><td>${i.standardNote?:'-'}</td><td><form method="post"><input type="hidden" name="action" value="retireItem"/><input type="hidden" name="itemId" value="${i.id}"/><button onclick="return confirm('Remove this item from future trolley handovers?')">Remove</button></form></td></tr><%}}%></tbody></table></div></section>
${ui.includeFragment("patienthandover","pagination",[pageName:"emergencyTrolleyItems",currentPage:binding.hasVariable('itemCurrentPage')?itemCurrentPage:1,totalPages:binding.hasVariable('itemTotalPages')?itemTotalPages:1,totalItems:binding.hasVariable('itemTotalItems')?itemTotalItems:0,parameters:[viewAll:false]])}
<%}%></div><script>function dismissNotice(button){var box=button.parentNode;if(box)box.style.display='none';}</script>